import type { NextPage } from 'next'
import { useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Octokit } from "@octokit/rest";

import data from '../mock-data.json';
import styles from '../styles/Home.module.css'

const Home: NextPage<{ runs: any }> = ({runs}) => {
  useEffect(() => {
    console.log(runs[0])
    console.log(runs.length)
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  if (process.env.USE_MOCK_DATA === "true") {
    return {
      props: {
        runs: data,
      },
    }
  } else {
    const octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN,
    });

    const workflows = await octokit.rest.actions.listRepoWorkflows({
      owner: process.env.GITHUB_ORG as string,
      repo: process.env.GITHUB_REPO as string,
    });

    const workflowId = workflows.data.workflows.find(
      (workflow) => workflow.name === process.env.GITHUB_WORKFLOW
    )?.id;

    const runs = await octokit.paginate(octokit.actions.listWorkflowRuns, {
      owner: process.env.GITHUB_ORG as string,
      repo: process.env.GITHUB_REPO as string,
      workflow_id: workflowId as number,
      per_page: 100,
      event: "push",
    });

    return {
      props: {
        runs,
      },
    }
  }
}

export default Home
