name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          REPO_ORG: ${{ secrets.REPO_ORG }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_WORKFLOW: ${{ secrets.REPO_WORKFLOW }}
          REPO_BRANCH: ${{ secrets.REPO_BRANCH }}
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: yarn build
