name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          CONFIG: ${{ secrets.CONFIG }}
        run: yarn build
