name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          CONFIG: ${{ secrets.CONFIG }}
          MOCK_DATA: ${{ secrets.MOCK_DATA }}
          USE_MOCK_DATA: ${{ secrets.USE_MOCK_DATA }}
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          BRANCH: gh-pages
          FOLDER: out
